### ISSUE TITLE
Put jupyter into a persistent location

### ISSUE THREAD

**Issue by colearendt** [sol-eng/docker-r-session#18]
Rather than putting the jupyter install into a location like `/opt/python/3.5.3`, we should put into a location like `/opt/python/jupyter` and then register a python kernel. This will be a breaking change in the short term and take a bit more space, but will prevent breaking changes in the long term and make the images more interoperable with other infrastructure.

**Comment by koverholt** [comment]
Yes, this is a clean way to do things and keeps the Jupyter installation isolated from libraries used for analysis.

I would do it here in the Docker image, but for now things are consistent between this image, [installing Jupyter on a single server](https://docs.rstudio.com/rsp/integration/jupyter-standalone/), and [installing Jupyter on Slurm](https://docs.rstudio.com/rsp/integration/jupyter-slurm/).

To keep the consistency, we would need to add the [steps to register a new kernel](https://docs.rstudio.com/rsp/integration/jupyter-multiple-python-versions/) to all other Jupyter installation methods/targets. So I'm going to hold off on this optimization for now to keep things simple and avoid diverging too much at this point.

**Comment by colearendt** [comment]
@koverholt Any thoughts on eating this change along with the 1.3 release? I feel like this change will make this image (and our docs, as well as the environments built from the docs) much more reliable long term, so would love to see it prioritized with either 1.3 or 1.4 if it makes sense.

Happy to contribute to docs and such if that would be helpful!

**Comment by koverholt** [comment]
I don't see a pressing need to change this for 1.3 since this change would add more complexity than what is necessary for an example/base configuration of Launcher and Jupyter, and it would be inconsistent with how we currently recommend installing versions of R and Python.

Users can always add these customizations or optimizations to their own versions of these images if desired.

**Comment by koverholt** [comment]
As a follow up, there are two parts to this issue: 1) installing the Python env to `/opt/python/jupyter` instead of `/opt/python/<PYTHON_VERSION>`, and 2) installing additional Python envs and registering their kernels.

I can implement #1 to make the path consistent between image versions, but not #2 in this image for the sake of simplicity. That can be done as a downstream customization by users if needed.

**Comment by colearendt** [comment]
Yeah, item 1 is definitely my focus, because it allows these images (and others, potentially) to be used simultaneously (since RSP tethers to the location of Jupyter _globally_ and not just for a particular image).

**Comment by koverholt** [comment]
Thanks.

I was finally able to wrap my head around your request and saw some code from other places where we are doing this, so I think I have a solution for both item 1 and 2 in #24.

Seeing the code in other places was helpful for understanding what you meant by "put into a location like /opt/python/jupyter and then register a python kernel" that wasn't immediately apparent at first. And I tried to do it in a simple way that follows the simple configuration blocks that we do for other parts of this Docker image.

So I'll get that tested and merged.

**Comment by colearendt** [comment]
Woohoo!! Apologies for not explaining better 😄 Much appreciated sir!

**Comment by koverholt** [comment]
FYI, I am going to undo this change. Turned out to be a mess during testing. The main issues were:

1) Removing the default/built-in kernel was not working as expected. Removing the default kernel at `/opt/python/jupyter` does not work and leaves two kernels available, which goes against the purpose of the change. Also tried to overwrite the kernel named `python3`, but it ends up using `/opt/python/jupyter`, which is not the desired version.

2) If a user followed the docs at https://docs.rstudio.com/resources/install-python/ on their server and enabled the Local Launcher plugin as well as the Kubernetes plugin, they would have to change the installation on the server to match this more complicated setup with multiple versions of Python and registering kernels (which is only optional at the moment).

These issues violate the goal of this Dockerfile to be a simple starting point for a single version of Python and R by adding too much complexity and incompatibilities with our primary documented approach. Customizations like this can always be added to this image by the end user.

**Comment by colearendt** [comment]
I'm very curious about this. I'm also wondering whether we should change our recommendations at `install-python`. As a novice python user who followed those directions and then reaped the painful consequences when I mismatched my jupyter.conf when I switched from a server install to Kubernetes, and at one point had incompatible local + kubernetes versions, this pain feels like something avoidable.

I am of the opinion that this is one of the areas where we cut a corner on setup and it makes maintenance / utilization of the server longer term much more confusing / error prone. I think the small cost of learning how to register a kernel (when we have the user's attention and can walk them through it) makes things much simpler long term (especially while the launcher just bombs without much messaging when your `jupyter.conf` is configured wrong). The happy path here feels very narrow, and much more-so while our jupyter install is pegged to a version of python.

I'm also curious where things went sideways here as it is exactly the pattern being used on Colorado. Perhaps I am missing where the error showed up though:

![image](https://user-images.githubusercontent.com/23075542/78618576-f6187d80-7848-11ea-839d-4e71539cf1bb.png)

![image](https://user-images.githubusercontent.com/23075542/78618588-04ff3000-7849-11ea-9bf7-fbcd90026b8c.png)

https://github.com/rstudio/sol-eng-demo-server/blob/46476a58ef3e16401d720160a7f54d1c28352438/Dockerfile_multi#L210-L256

If there is any way I can help here - with testing, doc reviews, PR, etc. I'm happy to do so. Perhaps it's worth a discussion to flesh out what the best strategy is long term and then what steps we can take to get there. I definitely don't want to create too much more flailing. 😄 Apologies for the trouble!

**EDIT:** Also worth noting that I totally stole this pattern from @danielfrg , who blew my mind in the https://github.com/rstudio/rstudio-cloud-tools prep: https://github.com/rstudio/cloud-images/blob/0f085f3d27c108a826d60f032860dfd2238ee807/aws-marketplace/byol/rsp-bootstrap.sh#L34-L48

**Comment by koverholt** [comment]
I agree with all of those points, just not in this Docker image or the base installation steps right now, which will always represent the simplest cases and starting points that are easy to understand, test, and extend/customize.

I am very hesitant to change the common installation instructions for Python across all products on behalf of this small optimization (swapping images by changing the image version but not having to change the Python version/path) at the cost of increased complexity. The complexity of starting with multiple Python kernels from the start is much higher than having to bump the version of Python at upgrade time.

I would prefer to get more feedback from users about how to handle the base Python environment(s) better across all products as well as how to improve the functionality in RSP to handle multiple Python/Jupyter environments (similar to how you can configure one or more versions of Python in RSC) before we force a particular complex path.

It's not really a matter of more effort on our side in terms of PRs, testing, or doc reviews, it is a matter of starting simple and gathering feedback, usage patterns, and pain points from users based on a simple setup, otherwise we can lose our way in the complexity. We definitely want to improve the overall experience of managing Python environments, but not by starting with the most complex architecture and scenario with Docker and Kubernetes. And you or users can always use this image to make customizations as much as desired, while leaving the simplest path always available here as a starting point.

**Comment by koverholt** [comment]
Reverted to single Python installation in #28. Closing this as out of scope for these images at this time. We should instead consider this in the scope of docs or RSP/Launcher/Jupyter config and update these images as a later time based on changes to those layers instead of the other way around.
